#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx restart
echo "meto" > /var/run/nginx.pid
