#!/usr/bin/env bash
# This script will kill the 4-to_infinity_and_beyond process

# Get the PID of the process by its name
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Use kill to terminate the process
if [ -n "$pid" ]; then
  kill "$pid"
  echo "Process 4-to_infinity_and_beyond with PID $pid has been terminated."
else
  echo "Process not found."
fi
