#!/usr/bin/env bash
# Find the PID of the process
pid=$(pgrep -f "7-highlander")
# Check if the process is running
if [ -n "$pid" ]
then
    # Send a termination signal to the process
    pkill -SIGKILL -f "7-highlander"
    echo "Killed"
else
    echo "Process 7-highlander is not running."
fi