#!/usr/bin/env bash
# Parse Apache log file to display the visitor IP along with the HTTP status code.
# $1: Represents the first field (column) of each line in the input file.
# $9: Represents the ninth field (column) of each line in the input file.
# apache-access.log: This is the input file for awk. It specifies the file from which awk should read data.
awk '{print $1, $9}' apache-access.log
