#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
count=0
#The until loop continues executing the code block as long as the condition within the brackets is false.
# -eq is a comparison operator that checks if two operands are equal
until [ $count -eq 10 ]
do
  echo "Best School"
  ((count++))
done
