#!/usr/bin/env bash
# Write a Bash script that gives you information about the school file.

# -e is a condition that checks if the file exists.
if [ -e "school" ]
then
    echo "school file exists"
	# -s is a condition that checks if the file is not empty.
    if [ -s "school" ]
	then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
	# -f is a condition that checks if the file is a regular file.
    if [ -f "school" ]
	then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
